### ISSUE TITLE
Move the long term seasonal to the data.py module

### ISSUE THREAD

**Issue by UchechukwuUdenze** [UchechukwuUdenze/NHS_PostProcessing#11]
- ~Move it out of the plot function and have it exist on its own~
- ~it will probably be its own function~
- ~include optional arguments to also add it to the generate_dataframes functions as one of its 'aggregates'~
- ~Clean up the plot_seasonal function (maybe remove it completely and just use plot)~
- ~When dealing with the long term seasonal you might want to have multiple dataframes for mean, min, max, median and sum~

**Comment by UchechukwuUdenze** [comment]
When dealing with the long term seasonal you might want to have multiple dataframes for mean, min, max, median

**Comment by UchechukwuUdenze** [comment]
- custom df should also have an array of years as the input allowing it to skip years unlike the subset that selects everything

**Comment by UchechukwuUdenze** [comment]
Just a question Fuad, For the long-term seasonal aggregation, is the only means of aggregation going to be the mean or do I provide a way to ask the user to add how they want to aggregate?

**Comment by fuadyassin** [comment]
@UchechukwuUdenze  , as disscused you can make it optional for users, min, max, mean, median, sum, and quantiles. For the example plots, line plot for median/average, along with uncertainity band, min, max, and the quantiles like q1, and q3

**Comment by UchechukwuUdenze** [comment]
Noted

**Comment by UchechukwuUdenze** [comment]
Completed the fix in the data manipulation section

**Comment by UchechukwuUdenze** [comment]
- modify the title arg to be a string or a list of strings
- modify the naming convention of the plot savings to include the title as well as what it currently is.
- modify the plot seasonal func to use line, upper and lower as args all of which are lists of Dataframes where line is compulsory and the bounds are optional
- naming convention of the plot

**Comment by UchechukwuUdenze** [comment]
Include a transparency input to the function
when dealing with multiple bounds use multiples of the transparency input
modify 'line' to be a single input that can have "multiple upper and lower bounds in lists"
